/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as MarketingPricingRouteImport } from './routes/_marketing.pricing'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth.verify-otp'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppTeamSetupRouteImport } from './routes/_app.team-setup'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppQualificationRouteImport } from './routes/_app.qualification'
import { Route as AppProposalsRouteImport } from './routes/_app.proposals'
import { Route as AppOutreachRouteImport } from './routes/_app.outreach'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppMeetingsRouteImport } from './routes/_app.meetings'
import { Route as AppLeadGenerationRouteImport } from './routes/_app.lead-generation'
import { Route as AppKnowledgeBaseRouteImport } from './routes/_app.knowledge-base'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBillingRouteImport } from './routes/_app.billing'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppTeamSetupRoute = AppTeamSetupRouteImport.update({
  id: '/team-setup',
  path: '/team-setup',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQualificationRoute = AppQualificationRouteImport.update({
  id: '/qualification',
  path: '/qualification',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsRoute = AppProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachRoute = AppOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadGenerationRoute = AppLeadGenerationRouteImport.update({
  id: '/lead-generation',
  path: '/lead-generation',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBaseRoute = AppKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge-base': typeof AppKnowledgeBaseRoute
  '/lead-generation': typeof AppLeadGenerationRoute
  '/meetings': typeof AppMeetingsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/outreach': typeof AppOutreachRoute
  '/proposals': typeof AppProposalsRoute
  '/qualification': typeof AppQualificationRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/team-setup': typeof AppTeamSetupRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/pricing': typeof MarketingPricingRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge-base': typeof AppKnowledgeBaseRoute
  '/lead-generation': typeof AppLeadGenerationRoute
  '/meetings': typeof AppMeetingsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/outreach': typeof AppOutreachRoute
  '/proposals': typeof AppProposalsRoute
  '/qualification': typeof AppQualificationRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/team-setup': typeof AppTeamSetupRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/pricing': typeof MarketingPricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/knowledge-base': typeof AppKnowledgeBaseRoute
  '/_app/lead-generation': typeof AppLeadGenerationRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/outreach': typeof AppOutreachRoute
  '/_app/proposals': typeof AppProposalsRoute
  '/_app/qualification': typeof AppQualificationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/team-setup': typeof AppTeamSetupRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/': typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/knowledge-base'
    | '/lead-generation'
    | '/meetings'
    | '/onboarding'
    | '/outreach'
    | '/proposals'
    | '/qualification'
    | '/settings'
    | '/team'
    | '/team-setup'
    | '/login'
    | '/register'
    | '/verify-otp'
    | '/pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/knowledge-base'
    | '/lead-generation'
    | '/meetings'
    | '/onboarding'
    | '/outreach'
    | '/proposals'
    | '/qualification'
    | '/settings'
    | '/team'
    | '/team-setup'
    | '/login'
    | '/register'
    | '/verify-otp'
    | '/pricing'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_marketing'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/knowledge-base'
    | '/_app/lead-generation'
    | '/_app/meetings'
    | '/_app/onboarding'
    | '/_app/outreach'
    | '/_app/proposals'
    | '/_app/qualification'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/team-setup'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/verify-otp'
    | '/_marketing/pricing'
    | '/_marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/team-setup': {
      id: '/_app/team-setup'
      path: '/team-setup'
      fullPath: '/team-setup'
      preLoaderRoute: typeof AppTeamSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qualification': {
      id: '/_app/qualification'
      path: '/qualification'
      fullPath: '/qualification'
      preLoaderRoute: typeof AppQualificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposals': {
      id: '/_app/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AppProposalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach': {
      id: '/_app/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AppOutreachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lead-generation': {
      id: '/_app/lead-generation'
      path: '/lead-generation'
      fullPath: '/lead-generation'
      preLoaderRoute: typeof AppLeadGenerationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-base': {
      id: '/_app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AppKnowledgeBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKnowledgeBaseRoute: typeof AppKnowledgeBaseRoute
  AppLeadGenerationRoute: typeof AppLeadGenerationRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOutreachRoute: typeof AppOutreachRoute
  AppProposalsRoute: typeof AppProposalsRoute
  AppQualificationRoute: typeof AppQualificationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTeamSetupRoute: typeof AppTeamSetupRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKnowledgeBaseRoute: AppKnowledgeBaseRoute,
  AppLeadGenerationRoute: AppLeadGenerationRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOutreachRoute: AppOutreachRoute,
  AppProposalsRoute: AppProposalsRoute,
  AppQualificationRoute: AppQualificationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTeamSetupRoute: AppTeamSetupRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketingRouteChildren {
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
